-- definitions/euribor_new.sqlx
config {
    type: "table",
    description: "Table Euribor avec colonnes renommées pour l'analyse ACP",
    database: "financial-data-storage",
    schema: "clean_data_test"
}

SELECT
    Date,
    `1 jour` as jour_1,
    `1 semaine` as semaine_1,
    `1 mois` as mois_1,
    `3 mois` as mois_3,
    `6 mois` as mois_6,
    `12 mois` as mois_12
FROM ${ref("clean_data_preprod", "euribor")}
